version: 1.0.{build}
branches:
  only:
  - master
  - /.*-criteo.*/
image: Visual Studio 2015
init:
- git config --global core.autocrlf true
configuration:
- Release
environment:
  image_flag: 2015
build_script: build.cmd -release -BuildTests=False 
artifacts:
- path: '**\*.nupkg'

